### ISSUE TITLE
[Question]: Tests sometimes failed on GitHub action test

### ISSUE THREAD

**Issue by julienloizelet** [JanoPL/ddev-kibana#17]
Hi,

I'm using your add-on to test the [DDEV add-on test action](https://github.com/ddev/github-action-add-on-test) with a custom checkout action.

It works great, but, sometimes, test failed on the "green" assertion because the result is "yellow".  (maybe 2 failed on the last month)

For example: https://github.com/ddev/github-action-add-on-test/actions/runs/6182906096/job/16783556790

I don't see this kind of error on your repo test and I wonder if you have any idea of the root cause of this ? (and if there is something I could do to avoid this)

FYI, I'm testing with the v1.4.0 release of your add-on.

Thanks

**Comment by JanoPL** [comment]
Hi, 

I look at this and the yellow status is from Kibana when trying to connect to Elasticsearch, but in version 1.5.0 I added a config file to customize it. Maybe there is an error because CI checked out an old version without the config file and waited for the connection between kibana and elastic search

**Comment by rfay** [comment]
If there isn't a healthcheck for Elasticsearch (or Kibana) then these may be "ready" in the wrong order.

**Comment by JanoPL** [comment]
@rfay @julienloizelet I look at the workflow and, during execution, the CI uses the release version with the latest tag from the repo, even though it should use a specific tag (for example, 1.4.0).

throw error during testing release from repo, from directory it's working fine

![image](https://github.com/JanoPL/ddev-kibana/assets/37768741/64661c9a-8618-49d1-8617-491e1d139d4a)

so maybe there is missing ```ddev get <addon> --version```

**Comment by RandityaHundal** [comment]
It needs work

**Comment by JanoPL** [comment]
@julienloizelet I put logs from the Kibana service during the test and we can see why Kibana returns a yellow status.

I tried different options with your actions and the tests passed, but from the schedule I got the same error as you, so maybe the Kibana logs will show us what is happening during CI

**Comment by julienloizelet** [comment]
Hi @JanoPL ,

FYI, just have a failed job with logs (`not ok 2 install from directory`): https://github.com/ddev/github-action-add-on-test/actions/runs/6231944059/job/16914264276

but I can't figure out what's going on.

**Comment by rfay** [comment]
I don't really know anything that's going on here, but I note that the kibana healthcheck is

https://github.com/JanoPL/ddev-kibana/blob/e012b75b72ce699acfecf8509afcb330809f0cf2/docker-compose.kibana.yaml#L21-L25

And it's only checking local behavior, not checking whether elasticsearch is up. OTOH, it *does* have a dependency on elasticsearch, so that should theoretically mean that kibana has waited to start until elasticsearch was *ready* but I'm not completely sure docker-compose does that right.

https://github.com/JanoPL/ddev-kibana/blob/e012b75b72ce699acfecf8509afcb330809f0cf2/docker-compose.kibana.yaml#L19-L20

Anyway, in some other situations like this, I've seen the one container be ready before the container it depends on, and that definitely causes flaky tests with things you can't recreate doing it manually.

**Comment by JanoPL** [comment]
I also noticed that Docker only checks if Kibana is booted up and it doesn’t check if the connection is established to Elasticsearch.

I also saw a warning in the log about a missing encryption key with this message. So I added a pre-generated encryption key that should prevent invalidating the session.

```Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.```
